### ISSUE TITLE
Todo lista

### ISSUE THREAD

**Issue by warriormaster12** [warriormaster12/Metropolia_Chess#1]
- [ ] ruutu uhattu ottaa pawnit huomioon (ei normi pawn liikkeet mutta vain diagonaaliset viereiset)
- [ ] kysyy pelaajalta kuka on botti kuka on pelaaja
- [ ] undo botin kanssa
